language: ruby
rvm:
- 2.3.1
cache: bundler

before_install:
  - set -e
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      AWS_BUCKET="assets.datacite.org";
      MIDDLEMAN_ENV="production";
    else
      AWS_BUCKET="assets.labs.datacite.org";
      MIDDLEMAN_ENV="stage";
    fi

  - wget https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.2-1-amd64.deb
  - rm pandoc-1.15.2-1-amd64.deb

before_script:
  - cd vendor && npm install
  - cd ../

script:
  - bundle exec hologram -c hologram.yml
  - bundle exec middleman build --verbose -e $MIDDLEMAN_ENV

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  region: eu-west-1
  skip_cleanup: true
  local_dir: build
  acl: public_read
  cache_control: "max-age=31536000"
  on:
    all_branches: true
notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
