language: ruby
rvm:
- 2.3.1
cache: bundler

before_install:
  - set -e
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      AWS_BUCKET="assets.datacite.org";
    else
      AWS_BUCKET="assets.labs.datacite.org";
    fi

before_script:
  - cd vendor && npm install
  - cd ../

script:
  - bundle exec middleman build -e production

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  region: eu-west-1
  skip_cleanup: true
  local_dir: build
  acl: public_read
  cache_control: "max-age=31536000"
  on:
    repo: datacite/segugio
notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
