# Build settings
markdown: Pandoc
highlighter: rogue
gems:
  - jekyll-pandoc
  - jemoji
  - jekyll-paginate

exclude:
  - README.md
  - LICENCE
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - vendor
  - assets/jquery/*

sass:
  style: compressed

# Site settings
title: Assets
description: |
   Making research better by enabling people to find, share, use, and cite data.

email: support@datacite.org

name: 'DataCite'
author: 'DataCite'

permalink: /:title/
paginate: 10

url: "http://localhost:4000" # the base hostname & protocol for your site
baseurl: ""
source_url: https://github.com/datacite/segugio
cdn_url: https://assets.datacite.org
#used to display twitter cards
twitter_handle: '@datacite'

#fill in disqus shortname to use disqus
#disqus: datacite

#fill in tracking id
google_analytics: UA-22806196-6

#error tracking
bugsnag: c37a5861967091a9b42a1a77e235114a

# social icons and sharing options
social:
  - icon: twitter
    url:  https://twitter.com/datacite
    desc: Follow DataCite on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:  facebook
    url: https://facebook.com/???
    desc: Connect with DataCite on Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/datacite
    desc: Visit DataCite on Github
    share_url:
    share_title:
    share_link:

pandoc:
  extensions:
    - normalize
    - smart
    - mathjax
