name: Build
on:
  workflow_call:
    inputs:
      rack_env:
        required: true  
        type: string
      env_file:
        required: true
        type: string
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print basic info
        run: |
          echo "ENV_FILE INPUT: ${{ inputs.env_file }}"
          echo "RACK_ENV INPUT: ${{ inputs.rack_env }}"

      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Build
        run: |
          cp ${{ inputs.env_file }} .env
          bundle _1.17.3_ install --jobs 4 --retry 3
          yarn install
          wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
          sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb
          rm pandoc-1.19.2.1-1-amd64.deb
          bundle exec hologram -c hologram.yml
          bundle exec middleman build -e ${{ inputs.rack_env }}
          rm build/*.png build/*.gif
      - name: Cache
        uses: actions/cache@v3
        with:
          path: build
          key: assets-build-${{ github.sha }}
          restore-keys: |
            assets-build-${{ github.sha }}
