name: Deploy Main to Staging
on:
  push:
    branches:
      - "master"
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: print basic info
        run: |
          echo "REPOSITORY: ${{ github.repository }}"
          echo "BRANCH: ${{ github.ref_name }}"
